apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dp
  labels:
    app: frontend-app
    type: frontend
spec:           # spec POD
  selector:
    matchLabels:
      type: frontend    ## refenente o pod, linha 17.
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend-app
        type: frontend
    spec:
      containers:
      - name: frontend-container
        image: nginx:1.19.4
  replicas: 6
