apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql-app
spec:
  containers:
  - name: mysql-cont
    image: mysql:5
    env:  #criando variável de ambiente
      - name: MYSQL_ROOT_PASSWORD
        value: password  
      - name: MYSQL_DATABASE
        value: geekdb
